import math
def countalphabet(string):
    alphabet={}
    for i in string:
        if i not in alphabet:
            alphabet[i]=1
        else:
            alphabet[i]+=1
    print(sorted(alphabet.items(),key=lambda x:x[1],reverse=True))
countalphabet("OVSAOXQYVAMFKDNTFHWZKKWQLFCHHDMXGHVRXEICQQCZKKBZESGCKSSTFUKBXVAZXKWFJGUWWHWGHWIYVWBZEZWFJCTQGJSYWGGFNWQDKHOAJAVRJWUUZAVQJCBGUXUPKDSNQAVROCFQYGNHAGRBSDMEAHPRRWBTLPSYKLQETSZRZABMWZSGOLJPOVWFVWZHGFRFUXETKRCZRWBTLPSNTVESWBHUKTZZCSBUKSZEWRDRUHTPDWJVTYQYLVSJUJTOSUFRKLPPJSKVRDJPSBOAYOMCDSHVZTMQGFHUUMOSLVSLSSGMWDOEZWLEZSFROKAEAZZNIZIYUSHUGLBSWMKVRDAPWHVRXWETDZPRGFIYKKSERWBTLPSYKLQETSZRZABMWZSGOLJPDSHVZTMJWOVGNWZPOWZYHWIYSBGJKJTPLWHOKDMEAHPRRWBTLPSYKLQETSZRZABMWKVVYHMCOCFQYGNHAGRBSDMEAHPRRWBTLPSYKLQETSZRZABMWMSNNDMEAHPRCZQDHSFJUJLDGTKVYVWXDSHVZTMLFRKUKFBSWBWTNLQDUZCHJQBSWFSVYKBTDZOYOYPELVOGYZQYWGCASWASABSHTLQWLCABXJWHDSHVZTMTOOYRAHBZLVSFUMVOGTAHYAKXGHVRXEICQQCZKKBZESGCKSSTFUKBXVAZXKWFJGUWWHWGHWTPLWHOKDMEAHPRRWBTLPSLKSPWWHWGHWBSWFSJODTMWOBNTKEPJZSGOLJPDSHVZTMWWHWGHWTPLWHOKQMLZZSGOLJPLVSEKOQWDPSNTSVDOSFYKLQETSZRZABMWZSGOLJPDSHVZTMJWOVYKLQETSKUOKXPJKCEJKWQOWGQUETPLWHOK")
def decodeshifted(string):
    output=''
    for i in string:
        if i!='.':
            code=ord(i)
            code+=13
            if code>90:#Z
                code=64+(code-90)
            output+=chr(code)
        else:
            output+=(i+'\n')
    print(output)
#print(len("OVSAOXQYVAMFKDNTFHWZKKWQLFCHHDMXGHVRXEICQQCZKKBZESGCKSSTFUKBXVAZXKWFJGUWWHWGHWIYVWBZEZWFJCTQGJSYWGGFNWQDKHOAJAVRJWUUZAVQJCBGUXUPKDSNQAVROCFQYGNHAGRBSDMEAHPRRWBTLPSYKLQETSZRZABMWZSGOLJPOVWFVWZHGFRFUXETKRCZRWBTLPSNTVESWBHUKTZZCSBUKSZEWRDRUHTPDWJVTYQYLVSJUJTOSUFRKLPPJSKVRDJPSBOAYOMCDSHVZTMQGFHUUMOSLVSLSSGMWDOEZWLEZSFROKAEAZZNIZIYUSHUGLBSWMKVRDAPWHVRXWETDZPRGFIYKKSERWBTLPSYKLQETSZRZABMWZSGOLJPDSHVZTMJWOVGNWZPOWZYHWIYSBGJKJTPLWHOKDMEAHPRRWBTLPSYKLQETSZRZABMWKVVYHMCOCFQYGNHAGRBSDMEAHPRRWBTLPSYKLQETSZRZABMWMSNNDMEAHPRCZQDHSFJUJLDGTKVYVWXDSHVZTMLFRKUKFBSWBWTNLQDUZCHJQBSWFSVYKBTDZOYOYPELVOGYZQYWGCASWASABSHTLQWLCABXJWHDSHVZTMTOOYRAHBZLVSFUMVOGTAHYAKXGHVRXEICQQCZKKBZESGCKSSTFUKBXVAZXKWFJGUWWHWGHWTPLWHOKDMEAHPRRWBTLPSLKSPWWHWGHWBSWFSJODTMWOBNTKEPJZSGOLJPDSHVZTMWWHWGHWTPLWHOKQMLZZSGOLJPLVSEKOQWDPSNTSVDOSFYKLQETSZRZABMWZSGOLJPDSHVZTMJWOVYKLQETSKUOKXPJKCEJKWQOWGQUETPLWHOK"))