import math
def countalphabet(string):
    alphabet={}
    for i in string:
        if i not in alphabet:
            alphabet[i]=1
        else:
            alphabet[i]+=1
    print(alphabet)
#countalphabet("OVSAOXQYVAMFKDNTFHWZKKWQLFCHHDMXGHVRXEICQQCZKKBZESGCKSSTFUKBXVAZXKWFJGUWWHWGHWIYVWBZEZWFJCTQGJSYWGGFNWQDKHOAJAVRJWUUZAVQJCBGUXUPKDSNQAVROCFQYGNHAGRBSDMEAHPRRWBTLPSYKLQETSZRZABMWZSGOLJPOVWFVWZHGFRFUXETKRCZRWBTLPSNTVESWBHUKTZZCSBUKSZEWRDRUHTPDWJVTYQYLVSJUJTOSUFRKLPPJSKVRDJPSBOAYOMCDSHVZTMQGFHUUMOSLVSLSSGMWDOEZWLEZSFROKAEAZZNIZIYUSHUGLBSWMKVRDAPWHVRXWETDZPRGFIYKKSERWBTLPSYKLQETSZRZABMWZSGOLJPDSHVZTMJWOVGNWZPOWZYHWIYSBGJKJTPLWHOKDMEAHPRRWBTLPSYKLQETSZRZABMWKVVYHMCOCFQYGNHAGRBSDMEAHPRRWBTLPSYKLQETSZRZABMWMSNNDMEAHPRCZQDHSFJUJLDGTKVYVWXDSHVZTMLFRKUKFBSWBWTNLQDUZCHJQBSWFSVYKBTDZOYOYPELVOGYZQYWGCASWASABSHTLQWLCABXJWHDSHVZTMTOOYRAHBZLVSFUMVOGTAHYAKXGHVRXEICQQCZKKBZESGCKSSTFUKBXVAZXKWFJGUWWHWGHWTPLWHOKDMEAHPRRWBTLPSLKSPWWHWGHWBSWFSJODTMWOBNTKEPJZSGOLJPDSHVZTMWWHWGHWTPLWHOKQMLZZSGOLJPLVSEKOQWDPSNTSVDOSFYKLQETSZRZABMWZSGOLJPDSHVZTMJWOVYKLQETSKUOKXPJKCEJKWQOWGQUETPLWHOK")
def decodeshifted(string):
    output=''
    for i in string:
        if i!='.':
            code=ord(i)
            code+=13
            if code>90:#Z
                code=64+(code-90)
            output+=chr(code)
        else:
            output+=(i+'\n')
    print(output)
#print(len("OVSAOXQYVAMFKDNTFHWZKKWQLFCHHDMXGHVRXEICQQCZKKBZESGCKSSTFUKBXVAZXKWFJGUWWHWGHWIYVWBZEZWFJCTQGJSYWGGFNWQDKHOAJAVRJWUUZAVQJCBGUXUPKDSNQAVROCFQYGNHAGRBSDMEAHPRRWBTLPSYKLQETSZRZABMWZSGOLJPOVWFVWZHGFRFUXETKRCZRWBTLPSNTVESWBHUKTZZCSBUKSZEWRDRUHTPDWJVTYQYLVSJUJTOSUFRKLPPJSKVRDJPSBOAYOMCDSHVZTMQGFHUUMOSLVSLSSGMWDOEZWLEZSFROKAEAZZNIZIYUSHUGLBSWMKVRDAPWHVRXWETDZPRGFIYKKSERWBTLPSYKLQETSZRZABMWZSGOLJPDSHVZTMJWOVGNWZPOWZYHWIYSBGJKJTPLWHOKDMEAHPRRWBTLPSYKLQETSZRZABMWKVVYHMCOCFQYGNHAGRBSDMEAHPRRWBTLPSYKLQETSZRZABMWMSNNDMEAHPRCZQDHSFJUJLDGTKVYVWXDSHVZTMLFRKUKFBSWBWTNLQDUZCHJQBSWFSVYKBTDZOYOYPELVOGYZQYWGCASWASABSHTLQWLCABXJWHDSHVZTMTOOYRAHBZLVSFUMVOGTAHYAKXGHVRXEICQQCZKKBZESGCKSSTFUKBXVAZXKWFJGUWWHWGHWTPLWHOKDMEAHPRRWBTLPSLKSPWWHWGHWBSWFSJODTMWOBNTKEPJZSGOLJPDSHVZTMWWHWGHWTPLWHOKQMLZZSGOLJPLVSEKOQWDPSNTSVDOSFYKLQETSZRZABMWZSGOLJPDSHVZTMJWOVYKLQETSKUOKXPJKCEJKWQOWGQUETPLWHOK"))
for i in range(1,870):
    if 869%i==0:
        print(i,'\n')